config/routes.rb
Rails.application.routes.draw do
  get 'pages/sample'
  get 'pages/welcome'
  get 'pages/contact'
  root to: 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def sample
  end
  def welcome
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Almog Friedman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="header">
    <%= link_to "Almog Friedman", root_path, class: "logo"%>
    <div class="nav">
      <%= link_to "Home",root_path%>  |
      <%= link_to "Sample",pages_sample_path%>  |
      <%= link_to "Contact",pages_contact_path%>
    </div>
  </div>

  <div class="push">

  </div>
  <div class="body">
    <%= yield %>
  </div>

  <div class="footer">
    <small class="copyright">
      &copy All rights reserved to Almog Friedman 2016. See <a href="#">contact</a> page for more info
    </small>
  </div>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<div class="article">
  <h1>
    How to contact me
    <div class="seperator">
    </div>
  </h1>
  <p>
  	You can find me at anyone of these places:
  	<ul>
  		<li>
  			Mail: <a href="mailto:almogfr@gmail.com">almogfr@gmail.com</a>
  		</li>
      <li>
        Github: <a href="https://github.com/Teren9">https://github.com/Teren9</a>
      </li>
  		<li>
  			Twitter: <a href="https://twitter.com/teren9">@teren9</a>
  		</li>

  	</ul>
  </p>
</div>

app/views/pages/sample.html.erb
<div class="article">
  <h1>
    Hello, World!
    <div class="seperator">

    </div>
  </h1>
  <p>
    This is some random text <a href="#">with a link!</a>
  </p>

  <p>
  Single-origin coffee tousled thundercats vice humblebrag portland leggings tilde. Mlkshk cray squid tilde tumblr try-hard. Slow-carb dreamcatcher whatever organic beard tote bag. Yr roof party street art tacos typewriter banh mi, fashion axe VHS flexitarian selfies post-ironic. Fashion axe salvia green juice, direct trade next level small batch mumblecore. Typewriter bicycle rights portland quinoa shoreditch. Gastropub plaid hashtag actually, asymmetrical bushwick trust fund raw denim church-key pop-up yuccie next level.
  </p>
  <p>
  Craft beer dreamcatcher four loko deep v, banh mi organic poutine bushwick waistcoat swag DIY seitan etsy. Biodiesel butcher polaroid, blog thundercats lumbersexual beard poutine. Artisan pug messenger bag, scenester street art 8-bit next level kitsch art party gluten-free skateboard sustainable crucifix. Synth DIY farm-to-table, tattooed shabby chic +1 tilde 8-bit kombucha next level celiac williamsburg. Four loko waistcoat authentic, pop-up kitsch man braid scenester brooklyn godard try-hard sustainable butcher. Four dollar toast cliche twee, disrupt umami biodiesel mustache master cleanse pour-over scenester tote bag. Kale chips pitchfork sartorial, art party before they sold out lo-fi locavore mustache squid offal vegan.
  </p>
  <p>
  Knausgaard vinyl art party pinterest flannel wolf. DIY YOLO cliche cronut narwhal roof party. Kinfolk godard freegan, before they sold out keytar hammock pour-over whatever. Meh scenester vice, chillwave gentrify YOLO sriracha organic sartorial readymade cray mlkshk cardigan kale chips. Street art wolf disrupt, letterpress poutine try-hard cronut yuccie etsy austin kombucha vice master cleanse cardigan. Single-origin coffee kale chips biodiesel lomo kombucha, deep v artisan ugh. Pop-up semiotics cronut, fap butcher post-ironic pinterest.
  </p>
  <p>
  Drinking vinegar humblebrag master cleanse, direct trade fanny pack tote bag semiotics four loko. Butcher chambray retro bitters aesthetic, quinoa keffiyeh fanny pack scenester 90's slow-carb pop-up messenger bag. Selvage street art letterpress man bun, narwhal disrupt before they sold out kitsch pug fashion axe farm-to-table blue bottle. Meditation gluten-free waistcoat cold-pressed. Actually sustainable listicle, tofu selfies keytar craft beer gentrify. Waistcoat tofu shabby chic banjo kitsch, chia ugh vegan green juice fingerstache hoodie cliche gastropub four dollar toast. Tumblr VHS tofu, flannel sartorial hammock quinoa master cleanse fashion axe.
  </p>
  <p>
  Single-origin coffee tousled thundercats vice humblebrag portland leggings tilde. Mlkshk cray squid tilde tumblr try-hard. Slow-carb dreamcatcher whatever organic beard tote bag. Yr roof party street art tacos typewriter banh mi, fashion axe VHS flexitarian selfies post-ironic. Fashion axe salvia green juice, direct trade next level small batch mumblecore. Typewriter bicycle rights portland quinoa shoreditch. Gastropub plaid hashtag actually, asymmetrical bushwick trust fund raw denim church-key pop-up yuccie next level.
  </p>
  <p>
  Craft beer dreamcatcher four loko deep v, banh mi organic poutine bushwick waistcoat swag DIY seitan etsy. Biodiesel butcher polaroid, blog thundercats lumbersexual beard poutine. Artisan pug messenger bag, scenester street art 8-bit next level kitsch art party gluten-free skateboard sustainable crucifix. Synth DIY farm-to-table, tattooed shabby chic +1 tilde 8-bit kombucha next level celiac williamsburg. Four loko waistcoat authentic, pop-up kitsch man braid scenester brooklyn godard try-hard sustainable butcher. Four dollar toast cliche twee, disrupt umami biodiesel mustache master cleanse pour-over scenester tote bag. Kale chips pitchfork sartorial, art party before they sold out lo-fi locavore mustache squid offal vegan.
  </p>
</div>

<div class="article hebrew">
  <h1>
    שלום עולם!
    <div class="seperator">

    </div>
  </h1>
  <p>
    זהו מעט טקסט <a href="#">עם לינק!</a>
  </p>
  <p>
    לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית נולום ארווס סאפיאן - פוסיליס קוויס, אקווזמן קוואזי במר מודוף. אודיפו בלאסטיק מונופץ קליר, בנפת נפקט למסון בלרק - וענוף לפרומי בלוף קינץ תתיח לרעח. לת צשחמי לורם איפסום דולור סיט אמט, ליבם סולגק. בראיט ולחת צורק מונחף, בגורמי מגמש. תרבנך וסתעד לכנו סתשם השמה - לתכי מורגם בורק? לתיג ישבעס.
  </p>
  <p>
    סחטיר בלובק. תצטנפל בלינדו למרקל אס לכימפו, דול, צוט ומעיוט - לפתיעם ברשג - ולתיעם גדדיש. קוויז דומור ליאמום בלינך רוגצה. לפמעט מוסן מנת. מוסן מנת. להאמית קרהשק סכעיט דז מא, מנכם למטכין נשואי מנורך. נולום ארווס סאפיאן - פוסיליס קוויס, אקווזמן קוואזי במר מודוף. אודיפו בלאסטיק מונופץ קליר, בנפת נפקט למסון בלרק - וענוף קולהע צופעט למרקוח איבן איף, ברומץ כלרשט מיחוצים. קלאצי סחטיר בלובק. תצטנפל בלינדו למרקל אס לכימפו, דול, צוט ומעיוט - לפתיעם ברשג - ולתיעם גדדיש. קוויז דומור ליאמום בלינך רוגצה. לפמעט
  </p>
  <p>
    להאמית קרהשק סכעיט דז מא, מנכם למטכין נשואי מנורךגולר מונפרר סוברט לורם שבצק יהול, לכנוץ בעריר גק ליץ, ושבעגט. צש בליא, מנסוטו צמלח לביקו ננבי, צמוקו בלוקריה שיצמה ברורק. קולהע צופעט למרקוח איבן איף, ברומץ כלרשט מיחוצים. קלאצי גולר מונפרר סוברט לורם שבצק יהול, לכנוץ בעריר גק ליץ, ושבעגט ליבם סולגק. בראיט ולחת צורק מונחף, בגורמי מגמש. תרבנך וסתעד לכנו סתשם השמה - לתכי מורגם בורק? לתיג ישבעס.
  </p>
  <p>
    לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. קונדימנטום קורוס בליקרה, נונסטי קלובר בריקנה סטום, לפריקך תצטריק לרטי.
  </p>
  <p>
    גולר מונפרר סוברט לורם שבצק יהול, לכנוץ בעריר גק ליץ, ושבעגט ליבם סולגק. בראיט ולחת צורק מונחף, בגורמי מגמש. תרבנך וסתעד לכנו סתשם השמה - לתכי מורגם בורק? לתיג ישבעס.
  </p>
  <p>
    קולורס מונפרד אדנדום סילקוף, מרגשי ומרגשח. עמחליף
  </p>
</div>

app/views/pages/welcome.html.erb
<div class="article">
  <h1>
    Welcome!
    <div class="seperator"></div>
  </h1>
    <p>
      Hello and welcome to my online portfolio.
    </p>
    <p>
      My name is Almog Friedman and I'm currently studying Electrical Engeneering at the <a href="ariel.ac.il">University of Ariel</a>.
      I'm currently in my third year of my B.Sc degree.
    </p>
    <p>
      Other than that, my interests lay on a vast range of areas including: Computer Science, Systems Management, and more.
    </p>
    <p>
      The purpose of this site is to act as an all-in-one place for showing everything I do.
    </p>
  <p>
  	This site is yet very much under construction, but, if you want to contact me, you can find me here:
  	<ul>
  		<li>
  			Mail: <a href="mailto:almogfr@gmail.com">almogfr@gmail.com</a>
  		</li>
      <li>
        Github: <a href="https://github.com/Teren9">https://github.com/Teren9</a>
      </li>
  		<li>
  			Twitter: <a href="https://twitter.com/teren9">@teren9</a>
  		</li>

  	</ul>
  </p>
</div>